// County data with RUCC codes - Generated from USDA ERS Rural-Urban Continuum Codes 2023
// Generated on 2025-04-06T03:22:56.613Z
const countyData = {
  "AL": {
    "Autauga County": 2,
    "Baldwin County": 3,
    "Barbour County": 6,
    "Bibb County": 1,
    "Blount County": 1,
    "Bullock County": 8,
    "Butler County": 6,
    "Calhoun County": 3,
    "Chambers County": 6,
    "Cherokee County": 8,
    "Chilton County": 1,
    "Choctaw County": 9,
    "Clarke County": 9,
    "Clay County": 9,
    "Cleburne County": 8,
    "Coffee County": 4,
    "Colbert County": 3,
    "Conecuh County": 9,
    "Coosa County": 8,
    "Covington County": 6,
    "Crenshaw County": 8,
    "Cullman County": 4,
    "Dale County": 4,
    "Dallas County": 4,
    "DeKalb County": 6,
    "Elmore County": 2,
    "Escambia County": 6,
    "Etowah County": 3,
    "Fayette County": 8,
    "Franklin County": 6,
    "Geneva County": 3,
    "Greene County": 2,
    "Hale County": 2,
    "Henry County": 3,
    "Houston County": 3,
    "Jackson County": 6,
    "Jefferson County": 1,
    "Lamar County": 8,
    "Lauderdale County": 3,
    "Lawrence County": 3,
    "Lee County": 3,
    "Limestone County": 2,
    "Lowndes County": 2,
    "Macon County": 3,
    "Madison County": 2,
    "Marengo County": 6,
    "Marion County": 9,
    "Marshall County": 4,
    "Mobile County": 2,
    "Monroe County": 8,
    "Montgomery County": 2,
    "Morgan County": 3,
    "Perry County": 8,
    "Pickens County": 2,
    "Pike County": 6,
    "Randolph County": 8,
    "Russell County": 2,
    "St. Clair County": 1,
    "Shelby County": 1,
    "Sumter County": 8,
    "Talladega County": 4,
    "Tallapoosa County": 6,
    "Tuscaloosa County": 2,
    "Walker County": 1,
    "Washington County": 8,
    "Wilcox County": 9,
    "Winston County": 8
  },
  "AK": {
    "Aleutians East Borough": 9,
    "Aleutians West Census Area": 9,
    "Anchorage Municipality": 2,
    "Bethel Census Area": 7,
    "Bristol Bay Borough": 9,
    "Chugach Census Area": 9,
    "Copper River Census Area": 9,
    "Denali Borough": 9,
    "Dillingham Census Area": 9,
    "Fairbanks North Star Borough": 3,
    "Haines Borough": 9,
    "Hoonah-Angoon Census Area": 9,
    "Juneau City and Borough": 5,
    "Kenai Peninsula Borough": 7,
    "Ketchikan Gateway Borough": 7,
    "Kodiak Island Borough": 7,
    "Kusilvak Census Area": 9,
    "Lake and Peninsula Borough": 9,
    "Matanuska-Susitna Borough": 2,
    "Nome Census Area": 9,
    "North Slope Borough": 9,
    "Northwest Arctic Borough": 9,
    "Petersburg Borough": 9,
    "Prince of Wales-Hyder Census Area": 9,
    "Sitka City and Borough": 7,
    "Skagway Municipality": 9,
    "Southeast Fairbanks Census Area": 9,
    "Wrangell City and Borough": 9,
    "Yakutat City and Borough": 9,
    "Yukon-Koyukuk Census Area": 8
  },
  "AZ": {
    "Apache County": 8,
    "Cochise County": 3,
    "Coconino County": 3,
    "Gila County": 4,
    "Graham County": 7,
    "Greenlee County": 9,
    "La Paz County": 6,
    "Maricopa County": 1,
    "Mohave County": 3,
    "Navajo County": 4,
    "Pima County": 1,
    "Pinal County": 1,
    "Santa Cruz County": 6,
    "Yavapai County": 3,
    "Yuma County": 3
  },
  "AR": {
    "Arkansas County": 6,
    "Ashley County": 7,
    "Baxter County": 7,
    "Benton County": 2,
    "Boone County": 7,
    "Bradley County": 7,
    "Calhoun County": 9,
    "Carroll County": 6,
    "Chicot County": 9,
    "Clark County": 7,
    "Clay County": 9,
    "Cleburne County": 6,
    "Cleveland County": 8,
    "Columbia County": 7,
    "Conway County": 6,
    "Craighead County": 3,
    "Crawford County": 3,
    "Crittenden County": 1,
    "Cross County": 6,
    "Dallas County": 8,
    "Desha County": 9,
    "Drew County": 7,
    "Faulkner County": 2,
    "Franklin County": 8,
    "Fulton County": 9,
    "Garland County": 3,
    "Grant County": 2,
    "Greene County": 4,
    "Hempstead County": 6,
    "Hot Spring County": 6,
    "Howard County": 8,
    "Independence County": 7,
    "Izard County": 9,
    "Jackson County": 6,
    "Jefferson County": 4,
    "Johnson County": 7,
    "Lafayette County": 8,
    "Lawrence County": 6,
    "Lee County": 8,
    "Lincoln County": 9,
    "Little River County": 3,
    "Logan County": 8,
    "Lonoke County": 2,
    "Madison County": 2,
    "Marion County": 9,
    "Miller County": 3,
    "Mississippi County": 4,
    "Monroe County": 9,
    "Montgomery County": 8,
    "Nevada County": 9,
    "Newton County": 9,
    "Ouachita County": 7,
    "Perry County": 2,
    "Phillips County": 7,
    "Pike County": 9,
    "Poinsett County": 3,
    "Polk County": 7,
    "Pope County": 5,
    "Prairie County": 8,
    "Pulaski County": 2,
    "Randolph County": 7,
    "St. Francis County": 6,
    "Saline County": 2,
    "Scott County": 8,
    "Searcy County": 9,
    "Sebastian County": 3,
    "Sevier County": 6,
    "Sharp County": 9,
    "Stone County": 9,
    "Union County": 7,
    "Van Buren County": 8,
    "Washington County": 2,
    "White County": 4,
    "Woodruff County": 9,
    "Yell County": 9
  },
  "CA": {
    "Alameda County": 1,
    "Alpine County": 8,
    "Amador County": 6,
    "Butte County": 3,
    "Calaveras County": 6,
    "Colusa County": 6,
    "Contra Costa County": 1,
    "Del Norte County": 7,
    "El Dorado County": 1,
    "Fresno County": 1,
    "Glenn County": 6,
    "Humboldt County": 5,
    "Imperial County": 3,
    "Inyo County": 6,
    "Kern County": 2,
    "Kings County": 3,
    "Lake County": 4,
    "Lassen County": 7,
    "Los Angeles County": 1,
    "Madera County": 1,
    "Marin County": 1,
    "Mariposa County": 8,
    "Mendocino County": 4,
    "Merced County": 2,
    "Modoc County": 8,
    "Mono County": 7,
    "Monterey County": 2,
    "Napa County": 3,
    "Nevada County": 4,
    "Orange County": 1,
    "Placer County": 1,
    "Plumas County": 9,
    "Riverside County": 1,
    "Sacramento County": 1,
    "San Benito County": 1,
    "San Bernardino County": 1,
    "San Diego County": 1,
    "San Francisco County": 1,
    "San Joaquin County": 2,
    "San Luis Obispo County": 2,
    "San Mateo County": 1,
    "Santa Barbara County": 2,
    "Santa Clara County": 1,
    "Santa Cruz County": 2,
    "Shasta County": 3,
    "Sierra County": 8,
    "Siskiyou County": 7,
    "Solano County": 2,
    "Sonoma County": 2,
    "Stanislaus County": 2,
    "Sutter County": 3,
    "Tehama County": 4,
    "Trinity County": 8,
    "Tulare County": 2,
    "Tuolumne County": 4,
    "Ventura County": 2,
    "Yolo County": 1,
    "Yuba County": 3
  },
  "CO": {
    "Adams County": 1,
    "Alamosa County": 7,
    "Arapahoe County": 1,
    "Archuleta County": 7,
    "Baca County": 9,
    "Bent County": 9,
    "Boulder County": 2,
    "Broomfield County": 1,
    "Chaffee County": 6,
    "Cheyenne County": 9,
    "Clear Creek County": 1,
    "Conejos County": 9,
    "Costilla County": 9,
    "Crowley County": 8,
    "Custer County": 8,
    "Delta County": 6,
    "Denver County": 1,
    "Dolores County": 9,
    "Douglas County": 1,
    "Eagle County": 5,
    "Elbert County": 1,
    "El Paso County": 2,
    "Fremont County": 4,
    "Garfield County": 5,
    "Gilpin County": 1,
    "Grand County": 9,
    "Gunnison County": 7,
    "Hinsdale County": 9,
    "Huerfano County": 8,
    "Jackson County": 9,
    "Jefferson County": 1,
    "Kiowa County": 9,
    "Kit Carson County": 9,
    "Lake County": 9,
    "La Plata County": 6,
    "Larimer County": 2,
    "Las Animas County": 7,
    "Lincoln County": 8,
    "Logan County": 6,
    "Mesa County": 3,
    "Mineral County": 9,
    "Moffat County": 7,
    "Montezuma County": 6,
    "Montrose County": 5,
    "Morgan County": 6,
    "Otero County": 6,
    "Ouray County": 9,
    "Park County": 1,
    "Phillips County": 9,
    "Pitkin County": 7,
    "Prowers County": 7,
    "Pueblo County": 3,
    "Rio Blanco County": 9,
    "Rio Grande County": 9,
    "Routt County": 7,
    "Saguache County": 9,
    "San Juan County": 9,
    "San Miguel County": 9,
    "Sedgwick County": 9,
    "Summit County": 5,
    "Teller County": 2,
    "Washington County": 9,
    "Weld County": 2,
    "Yuma County": 9
  },
  "CT": {
    "Capitol Planning Region": 1,
    "Greater Bridgeport Planning Region": 2,
    "Lower Connecticut River Valley Planning Region": 1,
    "Naugatuck Valley Planning Region": 2,
    "Northeastern Connecticut Planning Region": 4,
    "Northwest Hills Planning Region": 4,
    "South Central Connecticut Planning Region": 2,
    "Southeastern Connecticut Planning Region": 2,
    "Western Connecticut Planning Region": 2
  },
  "DE": {
    "Kent County": 3,
    "New Castle County": 1,
    "Sussex County": 4
  },
  "DC": {
    "District of Columbia": 1
  },
  "FL": {
    "Alachua County": 2,
    "Baker County": 1,
    "Bay County": 3,
    "Bradford County": 6,
    "Brevard County": 2,
    "Broward County": 1,
    "Calhoun County": 8,
    "Charlotte County": 3,
    "Citrus County": 3,
    "Clay County": 1,
    "Collier County": 2,
    "Columbia County": 4,
    "DeSoto County": 6,
    "Dixie County": 8,
    "Duval County": 1,
    "Escambia County": 2,
    "Flagler County": 2,
    "Franklin County": 8,
    "Gadsden County": 2,
    "Gilchrist County": 2,
    "Glades County": 8,
    "Gulf County": 8,
    "Hamilton County": 8,
    "Hardee County": 6,
    "Hendry County": 4,
    "Hernando County": 1,
    "Highlands County": 3,
    "Hillsborough County": 1,
    "Holmes County": 8,
    "Indian River County": 3,
    "Jackson County": 6,
    "Jefferson County": 2,
    "Lafayette County": 9,
    "Lake County": 1,
    "Lee County": 2,
    "Leon County": 2,
    "Levy County": 2,
    "Liberty County": 8,
    "Madison County": 8,
    "Manatee County": 2,
    "Marion County": 2,
    "Martin County": 2,
    "Miami-Dade County": 1,
    "Monroe County": 4,
    "Nassau County": 1,
    "Okaloosa County": 2,
    "Okeechobee County": 4,
    "Orange County": 1,
    "Osceola County": 1,
    "Palm Beach County": 1,
    "Pasco County": 1,
    "Pinellas County": 1,
    "Polk County": 2,
    "Putnam County": 4,
    "St. Johns County": 1,
    "St. Lucie County": 2,
    "Santa Rosa County": 2,
    "Sarasota County": 2,
    "Seminole County": 1,
    "Sumter County": 3,
    "Suwannee County": 6,
    "Taylor County": 6,
    "Union County": 8,
    "Volusia County": 2,
    "Wakulla County": 2,
    "Walton County": 2,
    "Washington County": 3
  },
  "GA": {
    "Appling County": 7,
    "Atkinson County": 9,
    "Bacon County": 9,
    "Baker County": 8,
    "Baldwin County": 4,
    "Banks County": 8,
    "Barrow County": 1,
    "Bartow County": 1,
    "Ben Hill County": 7,
    "Berrien County": 8,
    "Bibb County": 3,
    "Bleckley County": 6,
    "Brantley County": 3,
    "Brooks County": 3,
    "Bryan County": 2,
    "Bulloch County": 4,
    "Burke County": 2,
    "Butts County": 1,
    "Calhoun County": 8,
    "Camden County": 4,
    "Candler County": 9,
    "Carroll County": 1,
    "Catoosa County": 2,
    "Charlton County": 8,
    "Chatham County": 2,
    "Chattahoochee County": 2,
    "Chattooga County": 6,
    "Cherokee County": 1,
    "Clarke County": 3,
    "Clay County": 9,
    "Clayton County": 1,
    "Clinch County": 8,
    "Cobb County": 1,
    "Coffee County": 7,
    "Colquitt County": 6,
    "Columbia County": 2,
    "Cook County": 6,
    "Coweta County": 1,
    "Crawford County": 3,
    "Crisp County": 6,
    "Dade County": 2,
    "Dawson County": 1,
    "Decatur County": 6,
    "DeKalb County": 1,
    "Dodge County": 7,
    "Dooly County": 8,
    "Dougherty County": 3,
    "Douglas County": 1,
    "Early County": 8,
    "Echols County": 3,
    "Effingham County": 2,
    "Elbert County": 6,
    "Emanuel County": 7,
    "Evans County": 8,
    "Fannin County": 8,
    "Fayette County": 1,
    "Floyd County": 3,
    "Forsyth County": 1,
    "Franklin County": 8,
    "Fulton County": 1,
    "Gilmer County": 6,
    "Glascock County": 9,
    "Glynn County": 3,
    "Gordon County": 4,
    "Grady County": 6,
    "Greene County": 8,
    "Gwinnett County": 1,
    "Habersham County": 6,
    "Hall County": 3,
    "Hancock County": 9,
    "Haralson County": 1,
    "Harris County": 2,
    "Hart County": 6,
    "Heard County": 1,
    "Henry County": 1,
    "Houston County": 3,
    "Irwin County": 9,
    "Jackson County": 4,
    "Jasper County": 1,
    "Jeff Davis County": 9,
    "Jefferson County": 8,
    "Jenkins County": 9,
    "Johnson County": 9,
    "Jones County": 3,
    "Lamar County": 6,
    "Lanier County": 3,
    "Laurens County": 4,
    "Lee County": 3,
    "Liberty County": 3,
    "Lincoln County": 2,
    "Long County": 3,
    "Lowndes County": 3,
    "Lumpkin County": 1,
    "McDuffie County": 2,
    "McIntosh County": 3,
    "Macon County": 8,
    "Madison County": 3,
    "Marion County": 2,
    "Meriwether County": 1,
    "Miller County": 9,
    "Mitchell County": 6,
    "Monroe County": 3,
    "Montgomery County": 9,
    "Morgan County": 1,
    "Murray County": 3,
    "Muscogee County": 2,
    "Newton County": 1,
    "Oconee County": 3,
    "Oglethorpe County": 3,
    "Paulding County": 1,
    "Peach County": 3,
    "Pickens County": 1,
    "Pierce County": 8,
    "Pike County": 1,
    "Polk County": 4,
    "Pulaski County": 8,
    "Putnam County": 8,
    "Quitman County": 8,
    "Rabun County": 9,
    "Randolph County": 8,
    "Richmond County": 2,
    "Rockdale County": 1,
    "Schley County": 8,
    "Screven County": 8,
    "Seminole County": 8,
    "Spalding County": 1,
    "Stephens County": 7,
    "Stewart County": 2,
    "Sumter County": 6,
    "Talbot County": 2,
    "Taliaferro County": 8,
    "Tattnall County": 8,
    "Taylor County": 8,
    "Telfair County": 9,
    "Terrell County": 3,
    "Thomas County": 4,
    "Tift County": 5,
    "Toombs County": 7,
    "Towns County": 9,
    "Treutlen County": 9,
    "Troup County": 4,
    "Turner County": 9,
    "Twiggs County": 3,
    "Union County": 8,
    "Upson County": 6,
    "Walker County": 2,
    "Walton County": 1,
    "Ware County": 5,
    "Warren County": 8,
    "Washington County": 7,
    "Wayne County": 6,
    "Webster County": 8,
    "Wheeler County": 9,
    "White County": 8,
    "Whitfield County": 3,
    "Wilcox County": 9,
    "Wilkes County": 8,
    "Wilkinson County": 8,
    "Worth County": 3
  },
  "HI": {
    "Hawaii County": 5,
    "Honolulu County": 1,
    "Kalawao County": 3,
    "Kauai County": 5,
    "Maui County": 3
  },
  "ID": {
    "Ada County": 2,
    "Adams County": 9,
    "Bannock County": 3,
    "Bear Lake County": 9,
    "Benewah County": 8,
    "Bingham County": 6,
    "Blaine County": 7,
    "Boise County": 2,
    "Bonner County": 6,
    "Bonneville County": 3,
    "Boundary County": 9,
    "Butte County": 3,
    "Camas County": 9,
    "Canyon County": 2,
    "Caribou County": 8,
    "Cassia County": 6,
    "Clark County": 8,
    "Clearwater County": 8,
    "Custer County": 8,
    "Elmore County": 6,
    "Franklin County": 3,
    "Fremont County": 8,
    "Gem County": 2,
    "Gooding County": 8,
    "Idaho County": 8,
    "Jefferson County": 3,
    "Jerome County": 3,
    "Kootenai County": 3,
    "Latah County": 4,
    "Lemhi County": 9,
    "Lewis County": 8,
    "Lincoln County": 8,
    "Madison County": 4,
    "Minidoka County": 7,
    "Nez Perce County": 3,
    "Oneida County": 8,
    "Owyhee County": 2,
    "Payette County": 6,
    "Power County": 8,
    "Shoshone County": 8,
    "Teton County": 9,
    "Twin Falls County": 3,
    "Valley County": 9,
    "Washington County": 6
  },
  "IL": {
    "Adams County": 5,
    "Alexander County": 3,
    "Bond County": 1,
    "Boone County": 2,
    "Brown County": 9,
    "Bureau County": 7,
    "Calhoun County": 1,
    "Carroll County": 9,
    "Cass County": 6,
    "Champaign County": 3,
    "Christian County": 6,
    "Clark County": 8,
    "Clay County": 9,
    "Clinton County": 1,
    "Coles County": 5,
    "Cook County": 1,
    "Crawford County": 6,
    "Cumberland County": 9,
    "DeKalb County": 1,
    "De Witt County": 6,
    "Douglas County": 8,
    "DuPage County": 1,
    "Edgar County": 6,
    "Edwards County": 9,
    "Effingham County": 7,
    "Fayette County": 6,
    "Ford County": 3,
    "Franklin County": 7,
    "Fulton County": 6,
    "Gallatin County": 8,
    "Greene County": 8,
    "Grundy County": 1,
    "Hamilton County": 9,
    "Hancock County": 9,
    "Hardin County": 9,
    "Henderson County": 9,
    "Henry County": 2,
    "Iroquois County": 8,
    "Jackson County": 5,
    "Jasper County": 9,
    "Jefferson County": 7,
    "Jersey County": 1,
    "Jo Daviess County": 8,
    "Johnson County": 8,
    "Kane County": 1,
    "Kankakee County": 3,
    "Kendall County": 1,
    "Knox County": 4,
    "Lake County": 1,
    "LaSalle County": 4,
    "Lawrence County": 9,
    "Lee County": 6,
    "Livingston County": 6,
    "Logan County": 6,
    "McDonough County": 7,
    "McHenry County": 1,
    "McLean County": 3,
    "Macon County": 3,
    "Macoupin County": 1,
    "Madison County": 1,
    "Marion County": 7,
    "Marshall County": 2,
    "Mason County": 8,
    "Massac County": 3,
    "Menard County": 3,
    "Mercer County": 2,
    "Monroe County": 1,
    "Montgomery County": 6,
    "Morgan County": 4,
    "Moultrie County": 8,
    "Ogle County": 6,
    "Peoria County": 2,
    "Perry County": 7,
    "Piatt County": 3,
    "Pike County": 9,
    "Pope County": 8,
    "Pulaski County": 8,
    "Putnam County": 8,
    "Randolph County": 6,
    "Richland County": 7,
    "Rock Island County": 2,
    "St. Clair County": 1,
    "Saline County": 7,
    "Sangamon County": 3,
    "Schuyler County": 9,
    "Scott County": 9,
    "Shelby County": 8,
    "Stark County": 2,
    "Stephenson County": 4,
    "Tazewell County": 2,
    "Union County": 6,
    "Vermilion County": 4,
    "Wabash County": 7,
    "Warren County": 6,
    "Washington County": 8,
    "Wayne County": 9,
    "White County": 6,
    "Whiteside County": 4,
    "Will County": 1,
    "Williamson County": 5,
    "Winnebago County": 2,
    "Woodford County": 2
  },
  "IN": {
    "Adams County": 6,
    "Allen County": 2,
    "Bartholomew County": 3,
    "Benton County": 3,
    "Blackford County": 6,
    "Boone County": 1,
    "Brown County": 1,
    "Carroll County": 3,
    "Cass County": 4,
    "Clark County": 1,
    "Clay County": 3,
    "Clinton County": 6,
    "Crawford County": 8,
    "Daviess County": 7,
    "Dearborn County": 1,
    "Decatur County": 6,
    "DeKalb County": 4,
    "Delaware County": 3,
    "Dubois County": 5,
    "Elkhart County": 3,
    "Fayette County": 6,
    "Floyd County": 1,
    "Fountain County": 8,
    "Franklin County": 1,
    "Fulton County": 7,
    "Gibson County": 6,
    "Grant County": 4,
    "Greene County": 6,
    "Hamilton County": 1,
    "Hancock County": 1,
    "Harrison County": 1,
    "Hendricks County": 1,
    "Henry County": 6,
    "Howard County": 3,
    "Huntington County": 6,
    "Jackson County": 4,
    "Jasper County": 1,
    "Jay County": 6,
    "Jefferson County": 6,
    "Jennings County": 6,
    "Johnson County": 1,
    "Knox County": 7,
    "Kosciusko County": 4,
    "LaGrange County": 8,
    "Lake County": 1,
    "LaPorte County": 3,
    "Lawrence County": 6,
    "Madison County": 1,
    "Marion County": 1,
    "Marshall County": 6,
    "Martin County": 9,
    "Miami County": 6,
    "Monroe County": 3,
    "Montgomery County": 6,
    "Morgan County": 1,
    "Newton County": 1,
    "Noble County": 6,
    "Ohio County": 1,
    "Orange County": 8,
    "Owen County": 3,
    "Parke County": 8,
    "Perry County": 7,
    "Pike County": 8,
    "Porter County": 1,
    "Posey County": 2,
    "Pulaski County": 8,
    "Putnam County": 6,
    "Randolph County": 6,
    "Ripley County": 6,
    "Rush County": 6,
    "St. Joseph County": 2,
    "Scott County": 6,
    "Shelby County": 1,
    "Spencer County": 8,
    "Starke County": 8,
    "Steuben County": 7,
    "Sullivan County": 3,
    "Switzerland County": 8,
    "Tippecanoe County": 3,
    "Tipton County": 1,
    "Union County": 8,
    "Vanderburgh County": 2,
    "Vermillion County": 3,
    "Vigo County": 3,
    "Wabash County": 6,
    "Warren County": 3,
    "Warrick County": 2,
    "Washington County": 1,
    "Wayne County": 5,
    "Wells County": 2,
    "White County": 6,
    "Whitley County": 2
  },
  "IA": {
    "Adair County": 8,
    "Adams County": 9,
    "Allamakee County": 8,
    "Appanoose County": 7,
    "Audubon County": 9,
    "Benton County": 2,
    "Black Hawk County": 3,
    "Boone County": 3,
    "Bremer County": 3,
    "Buchanan County": 6,
    "Buena Vista County": 7,
    "Butler County": 8,
    "Calhoun County": 9,
    "Carroll County": 7,
    "Cass County": 6,
    "Cedar County": 8,
    "Cerro Gordo County": 5,
    "Cherokee County": 9,
    "Chickasaw County": 8,
    "Clarke County": 6,
    "Clay County": 7,
    "Clayton County": 8,
    "Clinton County": 4,
    "Crawford County": 7,
    "Dallas County": 2,
    "Davis County": 9,
    "Decatur County": 9,
    "Delaware County": 8,
    "Des Moines County": 5,
    "Dickinson County": 7,
    "Dubuque County": 3,
    "Emmet County": 7,
    "Fayette County": 6,
    "Floyd County": 7,
    "Franklin County": 9,
    "Fremont County": 8,
    "Greene County": 8,
    "Grundy County": 3,
    "Guthrie County": 2,
    "Hamilton County": 6,
    "Hancock County": 9,
    "Hardin County": 6,
    "Harrison County": 2,
    "Henry County": 6,
    "Howard County": 8,
    "Humboldt County": 7,
    "Ida County": 8,
    "Iowa County": 8,
    "Jackson County": 6,
    "Jasper County": 2,
    "Jefferson County": 7,
    "Johnson County": 3,
    "Jones County": 2,
    "Keokuk County": 8,
    "Kossuth County": 7,
    "Lee County": 7,
    "Linn County": 2,
    "Louisa County": 8,
    "Lucas County": 8,
    "Lyon County": 8,
    "Madison County": 2,
    "Mahaska County": 7,
    "Marion County": 6,
    "Marshall County": 4,
    "Mills County": 2,
    "Mitchell County": 9,
    "Monona County": 8,
    "Monroe County": 9,
    "Montgomery County": 6,
    "Muscatine County": 4,
    "O'Brien County": 7,
    "Osceola County": 9,
    "Page County": 6,
    "Palo Alto County": 9,
    "Plymouth County": 6,
    "Pocahontas County": 9,
    "Polk County": 2,
    "Pottawattamie County": 2,
    "Poweshiek County": 6,
    "Ringgold County": 9,
    "Sac County": 9,
    "Scott County": 2,
    "Shelby County": 8,
    "Sioux County": 6,
    "Story County": 3,
    "Tama County": 6,
    "Taylor County": 9,
    "Union County": 6,
    "Van Buren County": 9,
    "Wapello County": 5,
    "Warren County": 2,
    "Washington County": 3,
    "Wayne County": 9,
    "Webster County": 5,
    "Winnebago County": 9,
    "Winneshiek County": 7,
    "Woodbury County": 3,
    "Worth County": 9,
    "Wright County": 9
  },
  "KS": {
    "Allen County": 7,
    "Anderson County": 8,
    "Atchison County": 6,
    "Barber County": 9,
    "Barton County": 7,
    "Bourbon County": 6,
    "Brown County": 8,
    "Butler County": 2,
    "Chase County": 8,
    "Chautauqua County": 9,
    "Cherokee County": 3,
    "Cheyenne County": 9,
    "Clark County": 9,
    "Clay County": 8,
    "Cloud County": 7,
    "Coffey County": 8,
    "Comanche County": 9,
    "Cowley County": 4,
    "Crawford County": 4,
    "Decatur County": 9,
    "Dickinson County": 6,
    "Doniphan County": 3,
    "Douglas County": 3,
    "Edwards County": 9,
    "Elk County": 8,
    "Ellis County": 5,
    "Ellsworth County": 9,
    "Finney County": 5,
    "Ford County": 5,
    "Franklin County": 6,
    "Geary County": 3,
    "Gove County": 9,
    "Graham County": 9,
    "Grant County": 7,
    "Gray County": 9,
    "Greeley County": 9,
    "Greenwood County": 8,
    "Hamilton County": 9,
    "Harper County": 8,
    "Harvey County": 2,
    "Haskell County": 9,
    "Hodgeman County": 9,
    "Jackson County": 3,
    "Jefferson County": 3,
    "Jewell County": 9,
    "Johnson County": 1,
    "Kearny County": 9,
    "Kingman County": 8,
    "Kiowa County": 9,
    "Labette County": 7,
    "Lane County": 9,
    "Leavenworth County": 1,
    "Lincoln County": 9,
    "Linn County": 1,
    "Logan County": 9,
    "Lyon County": 4,
    "McPherson County": 7,
    "Marion County": 8,
    "Marshall County": 8,
    "Meade County": 9,
    "Miami County": 1,
    "Mitchell County": 9,
    "Montgomery County": 7,
    "Morris County": 8,
    "Morton County": 9,
    "Nemaha County": 9,
    "Neosho County": 7,
    "Ness County": 9,
    "Norton County": 9,
    "Osage County": 3,
    "Osborne County": 9,
    "Ottawa County": 9,
    "Pawnee County": 9,
    "Phillips County": 9,
    "Pottawatomie County": 3,
    "Pratt County": 7,
    "Rawlins County": 9,
    "Reno County": 4,
    "Republic County": 9,
    "Rice County": 9,
    "Riley County": 3,
    "Rooks County": 9,
    "Rush County": 9,
    "Russell County": 9,
    "Saline County": 5,
    "Scott County": 9,
    "Sedgwick County": 2,
    "Seward County": 7,
    "Shawnee County": 3,
    "Sheridan County": 9,
    "Sherman County": 9,
    "Smith County": 9,
    "Stafford County": 9,
    "Stanton County": 9,
    "Stevens County": 9,
    "Sumner County": 2,
    "Thomas County": 7,
    "Trego County": 9,
    "Wabaunsee County": 3,
    "Wallace County": 9,
    "Washington County": 9,
    "Wichita County": 9,
    "Wilson County": 9,
    "Woodson County": 9,
    "Wyandotte County": 1
  },
  "KY": {
    "Adair County": 7,
    "Allen County": 3,
    "Anderson County": 6,
    "Ballard County": 3,
    "Barren County": 6,
    "Bath County": 8,
    "Bell County": 7,
    "Boone County": 1,
    "Bourbon County": 2,
    "Boyd County": 2,
    "Boyle County": 7,
    "Bracken County": 1,
    "Breathitt County": 9,
    "Breckinridge County": 8,
    "Bullitt County": 1,
    "Butler County": 3,
    "Caldwell County": 7,
    "Calloway County": 7,
    "Campbell County": 1,
    "Carlisle County": 3,
    "Carroll County": 6,
    "Carter County": 2,
    "Casey County": 9,
    "Christian County": 2,
    "Clark County": 2,
    "Clay County": 9,
    "Clinton County": 9,
    "Crittenden County": 8,
    "Cumberland County": 9,
    "Daviess County": 3,
    "Edmonson County": 3,
    "Elliott County": 8,
    "Estill County": 8,
    "Fayette County": 2,
    "Fleming County": 9,
    "Floyd County": 7,
    "Franklin County": 4,
    "Fulton County": 9,
    "Gallatin County": 1,
    "Garrard County": 8,
    "Grant County": 1,
    "Graves County": 6,
    "Grayson County": 6,
    "Green County": 8,
    "Greenup County": 2,
    "Hancock County": 8,
    "Hardin County": 3,
    "Harlan County": 7,
    "Harrison County": 6,
    "Hart County": 8,
    "Henderson County": 4,
    "Henry County": 1,
    "Hickman County": 8,
    "Hopkins County": 5,
    "Jackson County": 9,
    "Jefferson County": 1,
    "Jessamine County": 2,
    "Johnson County": 7,
    "Kenton County": 1,
    "Knott County": 9,
    "Knox County": 7,
    "Larue County": 3,
    "Laurel County": 5,
    "Lawrence County": 2,
    "Lee County": 9,
    "Leslie County": 9,
    "Letcher County": 9,
    "Lewis County": 8,
    "Lincoln County": 9,
    "Livingston County": 3,
    "Logan County": 6,
    "Lyon County": 8,
    "McCracken County": 3,
    "McCreary County": 9,
    "McLean County": 3,
    "Madison County": 4,
    "Magoffin County": 9,
    "Marion County": 6,
    "Marshall County": 8,
    "Martin County": 8,
    "Mason County": 6,
    "Meade County": 1,
    "Menifee County": 9,
    "Mercer County": 6,
    "Metcalfe County": 9,
    "Monroe County": 8,
    "Montgomery County": 6,
    "Morgan County": 9,
    "Muhlenberg County": 6,
    "Nelson County": 1,
    "Nicholas County": 8,
    "Ohio County": 6,
    "Oldham County": 1,
    "Owen County": 8,
    "Owsley County": 9,
    "Pendleton County": 1,
    "Perry County": 7,
    "Pike County": 7,
    "Powell County": 8,
    "Pulaski County": 5,
    "Robertson County": 8,
    "Rockcastle County": 9,
    "Rowan County": 6,
    "Russell County": 9,
    "Scott County": 2,
    "Shelby County": 1,
    "Simpson County": 6,
    "Spencer County": 1,
    "Taylor County": 7,
    "Todd County": 8,
    "Trigg County": 2,
    "Trimble County": 8,
    "Union County": 8,
    "Warren County": 3,
    "Washington County": 8,
    "Wayne County": 7,
    "Webster County": 9,
    "Whitley County": 7,
    "Wolfe County": 9,
    "Woodford County": 2
  },
  "LA": {
    "Acadia Parish": 2,
    "Allen Parish": 6,
    "Ascension Parish": 2,
    "Assumption Parish": 2,
    "Avoyelles Parish": 6,
    "Beauregard Parish": 6,
    "Bienville Parish": 8,
    "Bossier Parish": 2,
    "Caddo Parish": 2,
    "Calcasieu Parish": 2,
    "Caldwell Parish": 8,
    "Cameron Parish": 2,
    "Catahoula Parish": 9,
    "Claiborne Parish": 9,
    "Concordia Parish": 6,
    "De Soto Parish": 2,
    "East Baton Rouge Parish": 2,
    "East Carroll Parish": 8,
    "East Feliciana Parish": 2,
    "Evangeline Parish": 6,
    "Franklin Parish": 6,
    "Grant Parish": 3,
    "Iberia Parish": 4,
    "Iberville Parish": 2,
    "Jackson Parish": 6,
    "Jefferson Parish": 1,
    "Jefferson Davis Parish": 2,
    "Lafayette Parish": 2,
    "Lafourche Parish": 3,
    "LaSalle Parish": 8,
    "Lincoln Parish": 4,
    "Livingston Parish": 2,
    "Madison Parish": 6,
    "Morehouse Parish": 3,
    "Natchitoches Parish": 6,
    "Orleans Parish": 1,
    "Ouachita Parish": 3,
    "Plaquemines Parish": 1,
    "Pointe Coupee Parish": 2,
    "Rapides Parish": 3,
    "Red River Parish": 8,
    "Richland Parish": 3,
    "Sabine Parish": 8,
    "St. Bernard Parish": 1,
    "St. Charles Parish": 1,
    "St. Helena Parish": 2,
    "St. James Parish": 1,
    "St. John the Baptist Parish": 1,
    "St. Landry Parish": 4,
    "St. Martin Parish": 2,
    "St. Mary Parish": 4,
    "St. Tammany Parish": 2,
    "Tangipahoa Parish": 3,
    "Tensas Parish": 9,
    "Terrebonne Parish": 3,
    "Union Parish": 3,
    "Vermilion Parish": 2,
    "Vernon Parish": 4,
    "Washington Parish": 6,
    "Webster Parish": 6,
    "West Baton Rouge Parish": 2,
    "West Carroll Parish": 8,
    "West Feliciana Parish": 2,
    "Winn Parish": 8
  },
  "ME": {
    "Androscoggin County": 3,
    "Aroostook County": 7,
    "Cumberland County": 2,
    "Franklin County": 8,
    "Hancock County": 8,
    "Kennebec County": 4,
    "Knox County": 7,
    "Lincoln County": 8,
    "Oxford County": 6,
    "Penobscot County": 3,
    "Piscataquis County": 8,
    "Sagadahoc County": 2,
    "Somerset County": 6,
    "Waldo County": 8,
    "Washington County": 9,
    "York County": 2
  },
  "MD": {
    "Allegany County": 4,
    "Anne Arundel County": 1,
    "Baltimore County": 1,
    "Calvert County": 3,
    "Caroline County": 6,
    "Carroll County": 1,
    "Cecil County": 1,
    "Charles County": 1,
    "Dorchester County": 6,
    "Frederick County": 1,
    "Garrett County": 8,
    "Harford County": 1,
    "Howard County": 1,
    "Kent County": 6,
    "Montgomery County": 1,
    "Prince George's County": 1,
    "Queen Anne's County": 1,
    "St. Mary's County": 3,
    "Somerset County": 3,
    "Talbot County": 6,
    "Washington County": 2,
    "Wicomico County": 3,
    "Worcester County": 4,
    "Baltimore city": 1
  },
  "MA": {
    "Barnstable County": 3,
    "Berkshire County": 3,
    "Bristol County": 1,
    "Dukes County": 7,
    "Essex County": 1,
    "Franklin County": 4,
    "Hampden County": 2,
    "Hampshire County": 3,
    "Middlesex County": 1,
    "Nantucket County": 7,
    "Norfolk County": 1,
    "Plymouth County": 1,
    "Suffolk County": 1,
    "Worcester County": 2
  },
  "MI": {
    "Alcona County": 9,
    "Alger County": 9,
    "Allegan County": 4,
    "Alpena County": 7,
    "Antrim County": 8,
    "Arenac County": 8,
    "Baraga County": 9,
    "Barry County": 1,
    "Bay County": 3,
    "Benzie County": 3,
    "Berrien County": 3,
    "Branch County": 6,
    "Calhoun County": 3,
    "Cass County": 2,
    "Charlevoix County": 7,
    "Cheboygan County": 7,
    "Chippewa County": 7,
    "Clare County": 8,
    "Clinton County": 2,
    "Crawford County": 9,
    "Delta County": 5,
    "Dickinson County": 7,
    "Eaton County": 2,
    "Emmet County": 7,
    "Genesee County": 2,
    "Gladwin County": 8,
    "Gogebic County": 7,
    "Grand Traverse County": 3,
    "Gratiot County": 6,
    "Hillsdale County": 6,
    "Houghton County": 5,
    "Huron County": 9,
    "Ingham County": 2,
    "Ionia County": 1,
    "Iosco County": 7,
    "Iron County": 9,
    "Isabella County": 4,
    "Jackson County": 3,
    "Kalamazoo County": 2,
    "Kalkaska County": 3,
    "Kent County": 1,
    "Keweenaw County": 9,
    "Lake County": 9,
    "Lapeer County": 1,
    "Leelanau County": 3,
    "Lenawee County": 4,
    "Livingston County": 1,
    "Luce County": 9,
    "Mackinac County": 9,
    "Macomb County": 1,
    "Manistee County": 6,
    "Marquette County": 5,
    "Mason County": 7,
    "Mecosta County": 6,
    "Menominee County": 7,
    "Midland County": 3,
    "Missaukee County": 8,
    "Monroe County": 3,
    "Montcalm County": 1,
    "Montmorency County": 9,
    "Muskegon County": 3,
    "Newaygo County": 6,
    "Oakland County": 1,
    "Oceana County": 8,
    "Ogemaw County": 9,
    "Ontonagon County": 9,
    "Osceola County": 9,
    "Oscoda County": 9,
    "Otsego County": 7,
    "Ottawa County": 1,
    "Presque Isle County": 9,
    "Roscommon County": 7,
    "Saginaw County": 3,
    "St. Clair County": 1,
    "St. Joseph County": 4,
    "Sanilac County": 8,
    "Schoolcraft County": 9,
    "Shiawassee County": 4,
    "Tuscola County": 6,
    "Van Buren County": 6,
    "Washtenaw County": 2,
    "Wayne County": 1,
    "Wexford County": 6
  },
  "MN": {
    "Aitkin County": 8,
    "Anoka County": 1,
    "Becker County": 6,
    "Beltrami County": 7,
    "Benton County": 3,
    "Big Stone County": 9,
    "Blue Earth County": 3,
    "Brown County": 6,
    "Carlton County": 2,
    "Carver County": 1,
    "Cass County": 9,
    "Chippewa County": 7,
    "Chisago County": 1,
    "Clay County": 3,
    "Clearwater County": 8,
    "Cook County": 9,
    "Cottonwood County": 9,
    "Crow Wing County": 4,
    "Dakota County": 1,
    "Dodge County": 3,
    "Douglas County": 6,
    "Faribault County": 8,
    "Fillmore County": 3,
    "Freeborn County": 7,
    "Goodhue County": 6,
    "Grant County": 9,
    "Hennepin County": 1,
    "Houston County": 3,
    "Hubbard County": 9,
    "Isanti County": 1,
    "Itasca County": 6,
    "Jackson County": 9,
    "Kanabec County": 8,
    "Kandiyohi County": 4,
    "Kittson County": 9,
    "Koochiching County": 7,
    "Lac qui Parle County": 9,
    "Lake County": 8,
    "Lake of the Woods County": 9,
    "Le Sueur County": 1,
    "Lincoln County": 9,
    "Lyon County": 7,
    "McLeod County": 4,
    "Mahnomen County": 8,
    "Marshall County": 8,
    "Martin County": 6,
    "Meeker County": 6,
    "Mille Lacs County": 1,
    "Morrison County": 6,
    "Mower County": 4,
    "Murray County": 9,
    "Nicollet County": 3,
    "Nobles County": 7,
    "Norman County": 8,
    "Olmsted County": 3,
    "Otter Tail County": 6,
    "Pennington County": 6,
    "Pine County": 8,
    "Pipestone County": 8,
    "Polk County": 3,
    "Pope County": 8,
    "Ramsey County": 1,
    "Red Lake County": 8,
    "Redwood County": 9,
    "Renville County": 9,
    "Rice County": 4,
    "Rock County": 2,
    "Roseau County": 9,
    "St. Louis County": 2,
    "Scott County": 1,
    "Sherburne County": 1,
    "Sibley County": 8,
    "Stearns County": 3,
    "Steele County": 5,
    "Stevens County": 7,
    "Swift County": 9,
    "Todd County": 8,
    "Traverse County": 9,
    "Wabasha County": 3,
    "Wadena County": 9,
    "Waseca County": 6,
    "Washington County": 1,
    "Watonwan County": 8,
    "Wilkin County": 8,
    "Winona County": 4,
    "Wright County": 1,
    "Yellow Medicine County": 9
  },
  "MS": {
    "Adams County": 7,
    "Alcorn County": 7,
    "Amite County": 8,
    "Attala County": 6,
    "Benton County": 1,
    "Bolivar County": 7,
    "Calhoun County": 9,
    "Carroll County": 8,
    "Chickasaw County": 9,
    "Choctaw County": 9,
    "Claiborne County": 8,
    "Clarke County": 9,
    "Clay County": 7,
    "Coahoma County": 6,
    "Copiah County": 2,
    "Covington County": 8,
    "DeSoto County": 1,
    "Forrest County": 3,
    "Franklin County": 9,
    "George County": 8,
    "Greene County": 8,
    "Grenada County": 7,
    "Hancock County": 2,
    "Harrison County": 2,
    "Hinds County": 2,
    "Holmes County": 2,
    "Humphreys County": 8,
    "Issaquena County": 9,
    "Itawamba County": 9,
    "Jackson County": 2,
    "Jasper County": 8,
    "Jefferson County": 9,
    "Jefferson Davis County": 8,
    "Jones County": 4,
    "Kemper County": 9,
    "Lafayette County": 4,
    "Lamar County": 3,
    "Lauderdale County": 5,
    "Lawrence County": 8,
    "Leake County": 8,
    "Lee County": 5,
    "Leflore County": 6,
    "Lincoln County": 6,
    "Lowndes County": 5,
    "Madison County": 2,
    "Marion County": 6,
    "Marshall County": 1,
    "Monroe County": 7,
    "Montgomery County": 9,
    "Neshoba County": 7,
    "Newton County": 8,
    "Noxubee County": 9,
    "Oktibbeha County": 5,
    "Panola County": 6,
    "Pearl River County": 6,
    "Perry County": 3,
    "Pike County": 6,
    "Pontotoc County": 9,
    "Prentiss County": 7,
    "Quitman County": 8,
    "Rankin County": 2,
    "Scott County": 2,
    "Sharkey County": 8,
    "Simpson County": 2,
    "Smith County": 8,
    "Stone County": 2,
    "Sunflower County": 7,
    "Tallahatchie County": 9,
    "Tate County": 1,
    "Tippah County": 8,
    "Tishomingo County": 8,
    "Tunica County": 1,
    "Union County": 7,
    "Walthall County": 9,
    "Warren County": 4,
    "Washington County": 5,
    "Wayne County": 9,
    "Webster County": 9,
    "Wilkinson County": 8,
    "Winston County": 9,
    "Yalobusha County": 9,
    "Yazoo County": 2
  },
  "MO": {
    "Adair County": 7,
    "Andrew County": 3,
    "Atchison County": 9,
    "Audrain County": 6,
    "Barry County": 6,
    "Barton County": 8,
    "Bates County": 1,
    "Benton County": 9,
    "Bollinger County": 3,
    "Boone County": 3,
    "Buchanan County": 3,
    "Butler County": 5,
    "Caldwell County": 1,
    "Callaway County": 3,
    "Camden County": 7,
    "Cape Girardeau County": 3,
    "Carroll County": 8,
    "Carter County": 9,
    "Cass County": 1,
    "Cedar County": 8,
    "Chariton County": 8,
    "Christian County": 2,
    "Clark County": 9,
    "Clay County": 1,
    "Clinton County": 1,
    "Cole County": 3,
    "Cooper County": 3,
    "Crawford County": 8,
    "Dade County": 8,
    "Dallas County": 2,
    "Daviess County": 8,
    "DeKalb County": 3,
    "Dent County": 9,
    "Douglas County": 8,
    "Dunklin County": 7,
    "Franklin County": 1,
    "Gasconade County": 8,
    "Gentry County": 8,
    "Greene County": 2,
    "Grundy County": 7,
    "Harrison County": 9,
    "Henry County": 6,
    "Hickory County": 8,
    "Holt County": 8,
    "Howard County": 3,
    "Howell County": 7,
    "Iron County": 9,
    "Jackson County": 1,
    "Jasper County": 3,
    "Jefferson County": 1,
    "Johnson County": 4,
    "Knox County": 9,
    "Laclede County": 6,
    "Lafayette County": 1,
    "Lawrence County": 6,
    "Lewis County": 9,
    "Lincoln County": 1,
    "Linn County": 9,
    "Livingston County": 7,
    "McDonald County": 8,
    "Macon County": 7,
    "Madison County": 9,
    "Maries County": 8,
    "Marion County": 7,
    "Mercer County": 9,
    "Miller County": 6,
    "Mississippi County": 8,
    "Moniteau County": 3,
    "Monroe County": 9,
    "Montgomery County": 8,
    "Morgan County": 8,
    "New Madrid County": 9,
    "Newton County": 3,
    "Nodaway County": 6,
    "Oregon County": 9,
    "Osage County": 3,
    "Ozark County": 9,
    "Pemiscot County": 7,
    "Perry County": 6,
    "Pettis County": 5,
    "Phelps County": 5,
    "Pike County": 8,
    "Platte County": 1,
    "Polk County": 2,
    "Pulaski County": 5,
    "Putnam County": 9,
    "Ralls County": 9,
    "Randolph County": 6,
    "Ray County": 1,
    "Reynolds County": 9,
    "Ripley County": 9,
    "St. Charles County": 1,
    "St. Clair County": 8,
    "Ste. Genevieve County": 8,
    "St. Francois County": 4,
    "St. Louis County": 1,
    "Saline County": 7,
    "Schuyler County": 9,
    "Scotland County": 9,
    "Scott County": 4,
    "Shannon County": 9,
    "Shelby County": 9,
    "Stoddard County": 6,
    "Stone County": 6,
    "Sullivan County": 9,
    "Taney County": 4,
    "Texas County": 9,
    "Vernon County": 6,
    "Warren County": 1,
    "Washington County": 8,
    "Wayne County": 9,
    "Webster County": 2,
    "Worth County": 9,
    "Wright County": 8,
    "St. Louis city": 1
  },
  "MT": {
    "Beaverhead County": 9,
    "Big Horn County": 8,
    "Blaine County": 9,
    "Broadwater County": 3,
    "Carbon County": 3,
    "Carter County": 9,
    "Cascade County": 3,
    "Chouteau County": 8,
    "Custer County": 7,
    "Daniels County": 9,
    "Dawson County": 7,
    "Deer Lodge County": 7,
    "Fallon County": 9,
    "Fergus County": 7,
    "Flathead County": 5,
    "Gallatin County": 3,
    "Garfield County": 9,
    "Glacier County": 9,
    "Golden Valley County": 8,
    "Granite County": 8,
    "Hill County": 7,
    "Jefferson County": 3,
    "Judith Basin County": 8,
    "Lake County": 6,
    "Lewis and Clark County": 3,
    "Liberty County": 9,
    "Lincoln County": 9,
    "McCone County": 9,
    "Madison County": 8,
    "Meagher County": 8,
    "Mineral County": 3,
    "Missoula County": 3,
    "Musselshell County": 8,
    "Park County": 6,
    "Petroleum County": 9,
    "Phillips County": 9,
    "Pondera County": 9,
    "Powder River County": 9,
    "Powell County": 8,
    "Prairie County": 9,
    "Ravalli County": 6,
    "Richland County": 7,
    "Roosevelt County": 9,
    "Rosebud County": 8,
    "Sanders County": 8,
    "Sheridan County": 9,
    "Silver Bow County": 5,
    "Stillwater County": 3,
    "Sweet Grass County": 8,
    "Teton County": 8,
    "Toole County": 9,
    "Treasure County": 8,
    "Valley County": 9,
    "Wheatland County": 9,
    "Wibaux County": 9,
    "Yellowstone County": 3
  },
  "NE": {
    "Adams County": 4,
    "Antelope County": 9,
    "Arthur County": 9,
    "Banner County": 8,
    "Blaine County": 9,
    "Boone County": 9,
    "Box Butte County": 7,
    "Boyd County": 9,
    "Brown County": 9,
    "Buffalo County": 4,
    "Burt County": 8,
    "Butler County": 8,
    "Cass County": 2,
    "Cedar County": 9,
    "Chase County": 9,
    "Cherry County": 9,
    "Cheyenne County": 7,
    "Clay County": 9,
    "Colfax County": 7,
    "Cuming County": 9,
    "Custer County": 9,
    "Dakota County": 3,
    "Dawes County": 9,
    "Dawson County": 7,
    "Deuel County": 9,
    "Dixon County": 8,
    "Dodge County": 4,
    "Douglas County": 2,
    "Dundy County": 9,
    "Fillmore County": 8,
    "Franklin County": 9,
    "Frontier County": 9,
    "Furnas County": 9,
    "Gage County": 6,
    "Garden County": 9,
    "Garfield County": 9,
    "Gosper County": 9,
    "Grant County": 9,
    "Greeley County": 8,
    "Hall County": 3,
    "Hamilton County": 8,
    "Harlan County": 9,
    "Hayes County": 9,
    "Hitchcock County": 9,
    "Holt County": 9,
    "Hooker County": 9,
    "Howard County": 3,
    "Jefferson County": 9,
    "Johnson County": 8,
    "Kearney County": 9,
    "Keith County": 9,
    "Keya Paha County": 9,
    "Kimball County": 8,
    "Knox County": 9,
    "Lancaster County": 2,
    "Lincoln County": 5,
    "Logan County": 9,
    "Loup County": 9,
    "McPherson County": 9,
    "Madison County": 5,
    "Merrick County": 3,
    "Morrill County": 9,
    "Nance County": 8,
    "Nemaha County": 9,
    "Nuckolls County": 9,
    "Otoe County": 6,
    "Pawnee County": 9,
    "Perkins County": 9,
    "Phelps County": 7,
    "Pierce County": 9,
    "Platte County": 5,
    "Polk County": 8,
    "Red Willow County": 7,
    "Richardson County": 9,
    "Rock County": 9,
    "Saline County": 6,
    "Sarpy County": 2,
    "Saunders County": 2,
    "Scotts Bluff County": 5,
    "Seward County": 2,
    "Sheridan County": 9,
    "Sherman County": 8,
    "Sioux County": 9,
    "Stanton County": 9,
    "Thayer County": 9,
    "Thomas County": 9,
    "Thurston County": 8,
    "Valley County": 9,
    "Washington County": 2,
    "Wayne County": 7,
    "Webster County": 9,
    "Wheeler County": 9,
    "York County": 6
  },
  "NV": {
    "Churchill County": 6,
    "Clark County": 1,
    "Douglas County": 4,
    "Elko County": 5,
    "Esmeralda County": 9,
    "Eureka County": 9,
    "Humboldt County": 7,
    "Lander County": 9,
    "Lincoln County": 8,
    "Lyon County": 2,
    "Mineral County": 8,
    "Nye County": 4,
    "Pershing County": 8,
    "Storey County": 2,
    "Washoe County": 2,
    "White Pine County": 9,
    "Carson City": 3
  },
  "NH": {
    "Belknap County": 4,
    "Carroll County": 6,
    "Cheshire County": 4,
    "Coos County": 7,
    "Grafton County": 5,
    "Hillsborough County": 2,
    "Merrimack County": 4,
    "Rockingham County": 1,
    "Strafford County": 1,
    "Sullivan County": 7
  },
  "NJ": {
    "Atlantic County": 2,
    "Bergen County": 1,
    "Burlington County": 1,
    "Camden County": 1,
    "Cape May County": 2,
    "Cumberland County": 3,
    "Essex County": 1,
    "Gloucester County": 1,
    "Hudson County": 1,
    "Hunterdon County": 1,
    "Mercer County": 2,
    "Middlesex County": 1,
    "Monmouth County": 1,
    "Morris County": 1,
    "Ocean County": 1,
    "Passaic County": 1,
    "Salem County": 1,
    "Somerset County": 1,
    "Sussex County": 1,
    "Union County": 1,
    "Warren County": 2
  },
  "NM": {
    "Bernalillo County": 2,
    "Catron County": 9,
    "Chaves County": 5,
    "Cibola County": 6,
    "Colfax County": 7,
    "Curry County": 5,
    "De Baca County": 9,
    "Do�a Ana County": 3,
    "Eddy County": 5,
    "Grant County": 7,
    "Guadalupe County": 9,
    "Harding County": 9,
    "Hidalgo County": 9,
    "Lea County": 5,
    "Lincoln County": 7,
    "Los Alamos County": 6,
    "Luna County": 6,
    "McKinley County": 5,
    "Mora County": 8,
    "Otero County": 4,
    "Quay County": 7,
    "Rio Arriba County": 6,
    "Roosevelt County": 7,
    "Sandoval County": 2,
    "San Juan County": 3,
    "San Miguel County": 6,
    "Santa Fe County": 3,
    "Sierra County": 6,
    "Socorro County": 6,
    "Taos County": 7,
    "Torrance County": 2,
    "Union County": 9,
    "Valencia County": 2
  },
  "NY": {
    "Albany County": 2,
    "Allegany County": 7,
    "Bronx County": 1,
    "Broome County": 3,
    "Cattaraugus County": 4,
    "Cayuga County": 4,
    "Chautauqua County": 4,
    "Chemung County": 3,
    "Chenango County": 6,
    "Clinton County": 4,
    "Columbia County": 6,
    "Cortland County": 4,
    "Delaware County": 8,
    "Dutchess County": 2,
    "Erie County": 1,
    "Essex County": 6,
    "Franklin County": 7,
    "Fulton County": 4,
    "Genesee County": 4,
    "Greene County": 6,
    "Hamilton County": 8,
    "Herkimer County": 2,
    "Jefferson County": 3,
    "Kings County": 1,
    "Lewis County": 8,
    "Livingston County": 1,
    "Madison County": 2,
    "Monroe County": 1,
    "Montgomery County": 4,
    "Nassau County": 1,
    "New York County": 1,
    "Niagara County": 1,
    "Oneida County": 2,
    "Onondaga County": 2,
    "Ontario County": 1,
    "Orange County": 2,
    "Orleans County": 1,
    "Oswego County": 2,
    "Otsego County": 7,
    "Putnam County": 1,
    "Queens County": 1,
    "Rensselaer County": 2,
    "Richmond County": 1,
    "Rockland County": 1,
    "St. Lawrence County": 4,
    "Saratoga County": 2,
    "Schenectady County": 2,
    "Schoharie County": 2,
    "Schuyler County": 8,
    "Seneca County": 6,
    "Steuben County": 4,
    "Suffolk County": 1,
    "Sullivan County": 6,
    "Tioga County": 3,
    "Tompkins County": 3,
    "Ulster County": 3,
    "Warren County": 3,
    "Washington County": 3,
    "Wayne County": 1,
    "Westchester County": 1,
    "Wyoming County": 8,
    "Yates County": 6
  },
  "NC": {
    "Alamance County": 3,
    "Alexander County": 2,
    "Alleghany County": 9,
    "Anson County": 1,
    "Ashe County": 9,
    "Avery County": 9,
    "Beaufort County": 6,
    "Bertie County": 9,
    "Bladen County": 8,
    "Brunswick County": 2,
    "Buncombe County": 2,
    "Burke County": 2,
    "Cabarrus County": 1,
    "Caldwell County": 2,
    "Camden County": 1,
    "Carteret County": 4,
    "Caswell County": 8,
    "Catawba County": 2,
    "Chatham County": 2,
    "Cherokee County": 9,
    "Chowan County": 8,
    "Clay County": 9,
    "Cleveland County": 4,
    "Columbus County": 6,
    "Craven County": 4,
    "Cumberland County": 2,
    "Currituck County": 1,
    "Dare County": 4,
    "Davidson County": 2,
    "Davie County": 2,
    "Duplin County": 8,
    "Durham County": 2,
    "Edgecombe County": 3,
    "Forsyth County": 2,
    "Franklin County": 1,
    "Gaston County": 1,
    "Gates County": 1,
    "Graham County": 9,
    "Granville County": 6,
    "Greene County": 8,
    "Guilford County": 2,
    "Halifax County": 4,
    "Harnett County": 4,
    "Haywood County": 4,
    "Henderson County": 2,
    "Hertford County": 8,
    "Hoke County": 2,
    "Hyde County": 9,
    "Iredell County": 1,
    "Jackson County": 7,
    "Johnston County": 1,
    "Jones County": 8,
    "Lee County": 4,
    "Lenoir County": 4,
    "Lincoln County": 1,
    "McDowell County": 6,
    "Macon County": 7,
    "Madison County": 2,
    "Martin County": 6,
    "Mecklenburg County": 1,
    "Mitchell County": 8,
    "Montgomery County": 8,
    "Moore County": 3,
    "Nash County": 3,
    "New Hanover County": 2,
    "Northampton County": 9,
    "Onslow County": 3,
    "Orange County": 2,
    "Pamlico County": 9,
    "Pasquotank County": 4,
    "Pender County": 2,
    "Perquimans County": 8,
    "Person County": 2,
    "Pitt County": 3,
    "Polk County": 8,
    "Randolph County": 2,
    "Richmond County": 4,
    "Robeson County": 4,
    "Rockingham County": 2,
    "Rowan County": 1,
    "Rutherford County": 4,
    "Sampson County": 6,
    "Scotland County": 6,
    "Stanly County": 6,
    "Stokes County": 2,
    "Surry County": 6,
    "Swain County": 9,
    "Transylvania County": 6,
    "Tyrrell County": 9,
    "Union County": 1,
    "Vance County": 6,
    "Wake County": 1,
    "Warren County": 8,
    "Washington County": 9,
    "Watauga County": 5,
    "Wayne County": 3,
    "Wilkes County": 6,
    "Wilson County": 4,
    "Yadkin County": 2,
    "Yancey County": 8
  },
  "ND": {
    "Adams County": 9,
    "Barnes County": 6,
    "Benson County": 9,
    "Billings County": 9,
    "Bottineau County": 8,
    "Bowman County": 9,
    "Burke County": 8,
    "Burleigh County": 3,
    "Cass County": 3,
    "Cavalier County": 9,
    "Dickey County": 9,
    "Divide County": 9,
    "Dunn County": 9,
    "Eddy County": 9,
    "Emmons County": 8,
    "Foster County": 9,
    "Golden Valley County": 9,
    "Grand Forks County": 3,
    "Grant County": 8,
    "Griggs County": 9,
    "Hettinger County": 9,
    "Kidder County": 8,
    "LaMoure County": 9,
    "Logan County": 9,
    "McHenry County": 3,
    "McIntosh County": 9,
    "McKenzie County": 7,
    "McLean County": 8,
    "Mercer County": 8,
    "Morton County": 3,
    "Mountrail County": 8,
    "Nelson County": 8,
    "Oliver County": 3,
    "Pembina County": 9,
    "Pierce County": 9,
    "Ramsey County": 7,
    "Ransom County": 8,
    "Renville County": 3,
    "Richland County": 6,
    "Rolette County": 9,
    "Sargent County": 9,
    "Sheridan County": 8,
    "Sioux County": 9,
    "Slope County": 9,
    "Stark County": 5,
    "Steele County": 8,
    "Stutsman County": 7,
    "Towner County": 9,
    "Traill County": 8,
    "Walsh County": 8,
    "Ward County": 3,
    "Wells County": 9,
    "Williams County": 5
  },
  "OH": {
    "Adams County": 8,
    "Allen County": 3,
    "Ashland County": 6,
    "Ashtabula County": 1,
    "Athens County": 4,
    "Auglaize County": 4,
    "Belmont County": 3,
    "Brown County": 1,
    "Butler County": 1,
    "Carroll County": 2,
    "Champaign County": 6,
    "Clark County": 3,
    "Clermont County": 1,
    "Clinton County": 6,
    "Columbiana County": 4,
    "Coshocton County": 7,
    "Crawford County": 4,
    "Cuyahoga County": 1,
    "Darke County": 6,
    "Defiance County": 6,
    "Delaware County": 1,
    "Erie County": 3,
    "Fairfield County": 1,
    "Fayette County": 6,
    "Franklin County": 1,
    "Fulton County": 2,
    "Gallia County": 6,
    "Geauga County": 1,
    "Greene County": 2,
    "Guernsey County": 6,
    "Hamilton County": 1,
    "Hancock County": 4,
    "Hardin County": 6,
    "Harrison County": 8,
    "Henry County": 6,
    "Highland County": 6,
    "Hocking County": 1,
    "Holmes County": 9,
    "Huron County": 4,
    "Jackson County": 7,
    "Jefferson County": 3,
    "Knox County": 6,
    "Lake County": 1,
    "Lawrence County": 2,
    "Licking County": 1,
    "Logan County": 4,
    "Lorain County": 1,
    "Lucas County": 2,
    "Madison County": 1,
    "Mahoning County": 2,
    "Marion County": 4,
    "Medina County": 1,
    "Meigs County": 8,
    "Mercer County": 7,
    "Miami County": 2,
    "Monroe County": 8,
    "Montgomery County": 2,
    "Morgan County": 8,
    "Morrow County": 1,
    "Muskingum County": 4,
    "Noble County": 9,
    "Ottawa County": 3,
    "Paulding County": 8,
    "Perry County": 1,
    "Pickaway County": 1,
    "Pike County": 9,
    "Portage County": 2,
    "Preble County": 6,
    "Putnam County": 6,
    "Richland County": 3,
    "Ross County": 4,
    "Sandusky County": 4,
    "Scioto County": 4,
    "Seneca County": 4,
    "Shelby County": 4,
    "Stark County": 2,
    "Summit County": 2,
    "Trumbull County": 2,
    "Tuscarawas County": 4,
    "Union County": 1,
    "Van Wert County": 6,
    "Vinton County": 8,
    "Warren County": 1,
    "Washington County": 4,
    "Wayne County": 4,
    "Williams County": 7,
    "Wood County": 2,
    "Wyandot County": 7
  },
  "OK": {
    "Adair County": 8,
    "Alfalfa County": 8,
    "Atoka County": 9,
    "Beaver County": 9,
    "Beckham County": 7,
    "Blaine County": 8,
    "Bryan County": 6,
    "Caddo County": 6,
    "Canadian County": 1,
    "Carter County": 5,
    "Cherokee County": 6,
    "Choctaw County": 9,
    "Cimarron County": 9,
    "Cleveland County": 1,
    "Coal County": 9,
    "Comanche County": 3,
    "Cotton County": 3,
    "Craig County": 6,
    "Creek County": 1,
    "Custer County": 5,
    "Delaware County": 6,
    "Dewey County": 9,
    "Ellis County": 9,
    "Garfield County": 3,
    "Garvin County": 6,
    "Grady County": 1,
    "Grant County": 8,
    "Greer County": 9,
    "Harmon County": 9,
    "Harper County": 9,
    "Haskell County": 8,
    "Hughes County": 9,
    "Jackson County": 7,
    "Jefferson County": 8,
    "Johnston County": 9,
    "Kay County": 4,
    "Kingfisher County": 8,
    "Kiowa County": 8,
    "Latimer County": 9,
    "Le Flore County": 6,
    "Lincoln County": 1,
    "Logan County": 1,
    "Love County": 9,
    "McClain County": 1,
    "McCurtain County": 7,
    "McIntosh County": 8,
    "Major County": 8,
    "Marshall County": 9,
    "Mayes County": 6,
    "Murray County": 9,
    "Muskogee County": 4,
    "Noble County": 8,
    "Nowata County": 8,
    "Okfuskee County": 8,
    "Oklahoma County": 1,
    "Okmulgee County": 1,
    "Osage County": 1,
    "Ottawa County": 6,
    "Pawnee County": 1,
    "Payne County": 4,
    "Pittsburg County": 7,
    "Pontotoc County": 7,
    "Pottawatomie County": 4,
    "Pushmataha County": 9,
    "Roger Mills County": 9,
    "Rogers County": 1,
    "Seminole County": 7,
    "Sequoyah County": 3,
    "Stephens County": 4,
    "Texas County": 7,
    "Tillman County": 8,
    "Tulsa County": 1,
    "Wagoner County": 1,
    "Washington County": 4,
    "Washita County": 9,
    "Woods County": 7,
    "Woodward County": 7
  },
  "OR": {
    "Baker County": 7,
    "Benton County": 3,
    "Clackamas County": 1,
    "Clatsop County": 4,
    "Columbia County": 1,
    "Coos County": 5,
    "Crook County": 3,
    "Curry County": 7,
    "Deschutes County": 3,
    "Douglas County": 4,
    "Gilliam County": 9,
    "Grant County": 9,
    "Harney County": 9,
    "Hood River County": 6,
    "Jackson County": 3,
    "Jefferson County": 3,
    "Josephine County": 3,
    "Klamath County": 5,
    "Lake County": 9,
    "Lane County": 2,
    "Lincoln County": 5,
    "Linn County": 3,
    "Malheur County": 6,
    "Marion County": 2,
    "Morrow County": 8,
    "Multnomah County": 1,
    "Polk County": 2,
    "Sherman County": 9,
    "Tillamook County": 7,
    "Umatilla County": 4,
    "Union County": 7,
    "Wallowa County": 9,
    "Wasco County": 7,
    "Washington County": 1,
    "Wheeler County": 9,
    "Yamhill County": 1
  },
  "PA": {
    "Adams County": 3,
    "Allegheny County": 1,
    "Armstrong County": 1,
    "Beaver County": 1,
    "Bedford County": 8,
    "Berks County": 2,
    "Blair County": 3,
    "Bradford County": 6,
    "Bucks County": 1,
    "Butler County": 1,
    "Cambria County": 3,
    "Cameron County": 9,
    "Carbon County": 2,
    "Centre County": 3,
    "Chester County": 1,
    "Clarion County": 6,
    "Clearfield County": 4,
    "Clinton County": 6,
    "Columbia County": 4,
    "Crawford County": 4,
    "Cumberland County": 2,
    "Dauphin County": 2,
    "Delaware County": 1,
    "Elk County": 7,
    "Erie County": 2,
    "Fayette County": 1,
    "Forest County": 9,
    "Franklin County": 3,
    "Fulton County": 8,
    "Greene County": 6,
    "Huntingdon County": 6,
    "Indiana County": 4,
    "Jefferson County": 7,
    "Juniata County": 8,
    "Lackawanna County": 2,
    "Lancaster County": 2,
    "Lawrence County": 1,
    "Lebanon County": 3,
    "Lehigh County": 2,
    "Luzerne County": 2,
    "Lycoming County": 3,
    "McKean County": 7,
    "Mercer County": 4,
    "Mifflin County": 4,
    "Monroe County": 4,
    "Montgomery County": 1,
    "Montour County": 6,
    "Northampton County": 2,
    "Northumberland County": 4,
    "Perry County": 2,
    "Philadelphia County": 1,
    "Pike County": 6,
    "Potter County": 9,
    "Schuylkill County": 4,
    "Snyder County": 7,
    "Somerset County": 6,
    "Sullivan County": 8,
    "Susquehanna County": 8,
    "Tioga County": 8,
    "Union County": 6,
    "Venango County": 4,
    "Warren County": 6,
    "Washington County": 1,
    "Wayne County": 6,
    "Westmoreland County": 1,
    "Wyoming County": 2,
    "York County": 2
  },
  "RI": {
    "Bristol County": 1,
    "Kent County": 1,
    "Newport County": 1,
    "Providence County": 1,
    "Washington County": 1
  },
  "SC": {
    "Abbeville County": 6,
    "Aiken County": 2,
    "Allendale County": 8,
    "Anderson County": 2,
    "Bamberg County": 9,
    "Barnwell County": 8,
    "Beaufort County": 3,
    "Berkeley County": 2,
    "Calhoun County": 2,
    "Charleston County": 2,
    "Cherokee County": 6,
    "Chester County": 1,
    "Chesterfield County": 6,
    "Clarendon County": 8,
    "Colleton County": 6,
    "Darlington County": 3,
    "Dillon County": 6,
    "Dorchester County": 2,
    "Edgefield County": 2,
    "Fairfield County": 2,
    "Florence County": 3,
    "Georgetown County": 4,
    "Greenville County": 2,
    "Greenwood County": 4,
    "Hampton County": 8,
    "Horry County": 2,
    "Jasper County": 3,
    "Kershaw County": 2,
    "Lancaster County": 1,
    "Laurens County": 2,
    "Lee County": 8,
    "Lexington County": 2,
    "McCormick County": 8,
    "Marion County": 6,
    "Marlboro County": 6,
    "Newberry County": 6,
    "Oconee County": 4,
    "Orangeburg County": 4,
    "Pickens County": 2,
    "Richland County": 2,
    "Saluda County": 2,
    "Spartanburg County": 2,
    "Sumter County": 3,
    "Union County": 2,
    "Williamsburg County": 6,
    "York County": 1
  },
  "SD": {
    "Aurora County": 9,
    "Beadle County": 7,
    "Bennett County": 9,
    "Bon Homme County": 9,
    "Brookings County": 5,
    "Brown County": 5,
    "Brule County": 9,
    "Buffalo County": 9,
    "Butte County": 7,
    "Campbell County": 9,
    "Charles Mix County": 9,
    "Clark County": 9,
    "Clay County": 6,
    "Codington County": 5,
    "Corson County": 9,
    "Custer County": 3,
    "Davison County": 7,
    "Day County": 9,
    "Deuel County": 9,
    "Dewey County": 9,
    "Douglas County": 9,
    "Edmunds County": 9,
    "Fall River County": 9,
    "Faulk County": 9,
    "Grant County": 9,
    "Gregory County": 9,
    "Haakon County": 9,
    "Hamlin County": 9,
    "Hand County": 9,
    "Hanson County": 8,
    "Harding County": 9,
    "Hughes County": 7,
    "Hutchinson County": 8,
    "Hyde County": 9,
    "Jackson County": 9,
    "Jerauld County": 9,
    "Jones County": 9,
    "Kingsbury County": 9,
    "Lake County": 6,
    "Lawrence County": 6,
    "Lincoln County": 2,
    "Lyman County": 9,
    "McCook County": 2,
    "McPherson County": 9,
    "Marshall County": 9,
    "Meade County": 3,
    "Mellette County": 9,
    "Miner County": 8,
    "Minnehaha County": 2,
    "Moody County": 8,
    "Oglala Lakota County": 9,
    "Pennington County": 3,
    "Perkins County": 9,
    "Potter County": 9,
    "Roberts County": 9,
    "Sanborn County": 9,
    "Spink County": 9,
    "Stanley County": 9,
    "Sully County": 9,
    "Todd County": 9,
    "Tripp County": 9,
    "Turner County": 2,
    "Union County": 3,
    "Walworth County": 9,
    "Yankton County": 7,
    "Ziebach County": 9
  },
  "TN": {
    "Anderson County": 2,
    "Bedford County": 4,
    "Benton County": 9,
    "Bledsoe County": 8,
    "Blount County": 2,
    "Bradley County": 3,
    "Campbell County": 2,
    "Cannon County": 1,
    "Carroll County": 6,
    "Carter County": 3,
    "Cheatham County": 1,
    "Chester County": 3,
    "Claiborne County": 6,
    "Clay County": 8,
    "Cocke County": 6,
    "Coffee County": 4,
    "Crockett County": 3,
    "Cumberland County": 4,
    "Davidson County": 1,
    "Decatur County": 9,
    "DeKalb County": 8,
    "Dickson County": 1,
    "Dyer County": 6,
    "Fayette County": 1,
    "Fentress County": 8,
    "Franklin County": 7,
    "Gibson County": 3,
    "Giles County": 6,
    "Grainger County": 2,
    "Greene County": 4,
    "Grundy County": 8,
    "Hamblen County": 3,
    "Hamilton County": 2,
    "Hancock County": 8,
    "Hardeman County": 6,
    "Hardin County": 6,
    "Hawkins County": 2,
    "Haywood County": 6,
    "Henderson County": 6,
    "Henry County": 7,
    "Hickman County": 1,
    "Houston County": 8,
    "Humphreys County": 8,
    "Jackson County": 8,
    "Jefferson County": 3,
    "Johnson County": 8,
    "Knox County": 2,
    "Lake County": 9,
    "Lauderdale County": 6,
    "Lawrence County": 6,
    "Lewis County": 8,
    "Lincoln County": 6,
    "Loudon County": 2,
    "McMinn County": 4,
    "McNairy County": 8,
    "Macon County": 1,
    "Madison County": 3,
    "Marion County": 2,
    "Marshall County": 6,
    "Maury County": 1,
    "Meigs County": 8,
    "Monroe County": 6,
    "Montgomery County": 2,
    "Moore County": 9,
    "Morgan County": 2,
    "Obion County": 7,
    "Overton County": 9,
    "Perry County": 9,
    "Pickett County": 9,
    "Polk County": 3,
    "Putnam County": 4,
    "Rhea County": 6,
    "Roane County": 2,
    "Robertson County": 1,
    "Rutherford County": 1,
    "Scott County": 8,
    "Sequatchie County": 2,
    "Sevier County": 4,
    "Shelby County": 1,
    "Smith County": 1,
    "Stewart County": 2,
    "Sullivan County": 2,
    "Sumner County": 1,
    "Tipton County": 1,
    "Trousdale County": 1,
    "Unicoi County": 3,
    "Union County": 2,
    "Van Buren County": 9,
    "Warren County": 6,
    "Washington County": 3,
    "Wayne County": 8,
    "Weakley County": 6,
    "White County": 7,
    "Williamson County": 1,
    "Wilson County": 1
  },
  "TX": {
    "Anderson County": 7,
    "Andrews County": 6,
    "Angelina County": 5,
    "Aransas County": 2,
    "Archer County": 3,
    "Armstrong County": 2,
    "Atascosa County": 1,
    "Austin County": 1,
    "Bailey County": 6,
    "Bandera County": 1,
    "Bastrop County": 1,
    "Baylor County": 9,
    "Bee County": 6,
    "Bell County": 2,
    "Bexar County": 1,
    "Blanco County": 8,
    "Borden County": 9,
    "Bosque County": 2,
    "Bowie County": 3,
    "Brazoria County": 1,
    "Brazos County": 2,
    "Brewster County": 7,
    "Briscoe County": 8,
    "Brooks County": 9,
    "Brown County": 5,
    "Burleson County": 2,
    "Burnet County": 6,
    "Caldwell County": 1,
    "Calhoun County": 6,
    "Callahan County": 3,
    "Cameron County": 2,
    "Camp County": 8,
    "Carson County": 2,
    "Cass County": 6,
    "Castro County": 9,
    "Chambers County": 1,
    "Cherokee County": 6,
    "Childress County": 9,
    "Clay County": 3,
    "Cochran County": 2,
    "Coke County": 8,
    "Coleman County": 8,
    "Collin County": 1,
    "Collingsworth County": 9,
    "Colorado County": 8,
    "Comal County": 1,
    "Comanche County": 9,
    "Concho County": 8,
    "Cooke County": 6,
    "Coryell County": 2,
    "Cottle County": 9,
    "Crane County": 8,
    "Crockett County": 8,
    "Crosby County": 2,
    "Culberson County": 9,
    "Dallam County": 7,
    "Dallas County": 1,
    "Dawson County": 6,
    "Deaf Smith County": 6,
    "Delta County": 8,
    "Denton County": 1,
    "DeWitt County": 6,
    "Dickens County": 8,
    "Dimmit County": 7,
    "Donley County": 8,
    "Duval County": 9,
    "Eastland County": 8,
    "Ector County": 3,
    "Edwards County": 9,
    "Ellis County": 1,
    "El Paso County": 2,
    "Erath County": 5,
    "Falls County": 2,
    "Fannin County": 6,
    "Fayette County": 6,
    "Fisher County": 8,
    "Floyd County": 8,
    "Foard County": 9,
    "Fort Bend County": 1,
    "Franklin County": 9,
    "Freestone County": 9,
    "Frio County": 6,
    "Gaines County": 6,
    "Galveston County": 1,
    "Garza County": 2,
    "Gillespie County": 7,
    "Glasscock County": 8,
    "Goliad County": 3,
    "Gonzales County": 6,
    "Gray County": 6,
    "Grayson County": 3,
    "Gregg County": 2,
    "Grimes County": 6,
    "Guadalupe County": 1,
    "Hale County": 4,
    "Hall County": 9,
    "Hamilton County": 8,
    "Hansford County": 9,
    "Hardeman County": 9,
    "Hardin County": 2,
    "Harris County": 1,
    "Harrison County": 2,
    "Hartley County": 9,
    "Haskell County": 8,
    "Hays County": 1,
    "Hemphill County": 9,
    "Henderson County": 4,
    "Hidalgo County": 2,
    "Hill County": 6,
    "Hockley County": 2,
    "Hood County": 4,
    "Hopkins County": 6,
    "Houston County": 7,
    "Howard County": 4,
    "Hudspeth County": 2,
    "Hunt County": 1,
    "Hutchinson County": 6,
    "Irion County": 3,
    "Jack County": 8,
    "Jackson County": 6,
    "Jasper County": 6,
    "Jeff Davis County": 9,
    "Jefferson County": 2,
    "Jim Hogg County": 8,
    "Jim Wells County": 6,
    "Johnson County": 1,
    "Jones County": 3,
    "Karnes County": 8,
    "Kaufman County": 1,
    "Kendall County": 1,
    "Kenedy County": 9,
    "Kent County": 9,
    "Kerr County": 4,
    "Kimble County": 9,
    "King County": 9,
    "Kinney County": 9,
    "Kleberg County": 4,
    "Knox County": 9,
    "Lamar County": 5,
    "Lamb County": 6,
    "Lampasas County": 2,
    "La Salle County": 8,
    "Lavaca County": 8,
    "Lee County": 8,
    "Leon County": 8,
    "Liberty County": 1,
    "Limestone County": 6,
    "Lipscomb County": 9,
    "Live Oak County": 8,
    "Llano County": 7,
    "Loving County": 9,
    "Lubbock County": 2,
    "Lynn County": 2,
    "McCulloch County": 9,
    "McLennan County": 2,
    "McMullen County": 8,
    "Madison County": 8,
    "Marion County": 8,
    "Martin County": 3,
    "Mason County": 9,
    "Matagorda County": 6,
    "Maverick County": 3,
    "Medina County": 1,
    "Menard County": 9,
    "Midland County": 3,
    "Milam County": 6,
    "Mills County": 9,
    "Mitchell County": 7,
    "Montague County": 6,
    "Montgomery County": 1,
    "Moore County": 7,
    "Morris County": 8,
    "Motley County": 8,
    "Nacogdoches County": 5,
    "Navarro County": 4,
    "Newton County": 8,
    "Nolan County": 6,
    "Nueces County": 2,
    "Ochiltree County": 7,
    "Oldham County": 2,
    "Orange County": 2,
    "Palo Pinto County": 6,
    "Panola County": 6,
    "Parker County": 1,
    "Parmer County": 9,
    "Pecos County": 7,
    "Polk County": 6,
    "Potter County": 2,
    "Presidio County": 9,
    "Rains County": 8,
    "Randall County": 2,
    "Reagan County": 8,
    "Real County": 9,
    "Red River County": 8,
    "Reeves County": 7,
    "Refugio County": 8,
    "Roberts County": 9,
    "Robertson County": 2,
    "Rockwall County": 1,
    "Runnels County": 8,
    "Rusk County": 2,
    "Sabine County": 9,
    "San Augustine County": 9,
    "San Jacinto County": 1,
    "San Patricio County": 2,
    "San Saba County": 9,
    "Schleicher County": 8,
    "Scurry County": 7,
    "Shackelford County": 8,
    "Shelby County": 7,
    "Sherman County": 9,
    "Smith County": 3,
    "Somervell County": 8,
    "Starr County": 4,
    "Stephens County": 7,
    "Sterling County": 8,
    "Stonewall County": 9,
    "Sutton County": 9,
    "Swisher County": 8,
    "Tarrant County": 1,
    "Taylor County": 3,
    "Terrell County": 9,
    "Terry County": 6,
    "Throckmorton County": 9,
    "Titus County": 7,
    "Tom Green County": 3,
    "Travis County": 1,
    "Trinity County": 8,
    "Tyler County": 8,
    "Upshur County": 2,
    "Upton County": 8,
    "Uvalde County": 6,
    "Val Verde County": 5,
    "Van Zandt County": 8,
    "Victoria County": 3,
    "Walker County": 4,
    "Waller County": 1,
    "Ward County": 6,
    "Washington County": 6,
    "Webb County": 2,
    "Wharton County": 4,
    "Wheeler County": 9,
    "Wichita County": 3,
    "Wilbarger County": 6,
    "Willacy County": 6,
    "Williamson County": 1,
    "Wilson County": 1,
    "Winkler County": 6,
    "Wise County": 1,
    "Wood County": 6,
    "Yoakum County": 9,
    "Young County": 7,
    "Zapata County": 6,
    "Zavala County": 7
  },
  "UT": {
    "Beaver County": 9,
    "Box Elder County": 4,
    "Cache County": 3,
    "Carbon County": 7,
    "Daggett County": 9,
    "Davis County": 2,
    "Duchesne County": 7,
    "Emery County": 9,
    "Garfield County": 9,
    "Grand County": 7,
    "Iron County": 4,
    "Juab County": 2,
    "Kane County": 8,
    "Millard County": 9,
    "Morgan County": 2,
    "Piute County": 9,
    "Rich County": 8,
    "Salt Lake County": 1,
    "San Juan County": 9,
    "Sanpete County": 6,
    "Sevier County": 7,
    "Summit County": 4,
    "Tooele County": 1,
    "Uintah County": 7,
    "Utah County": 2,
    "Wasatch County": 4,
    "Washington County": 3,
    "Wayne County": 9,
    "Weber County": 2
  },
  "VT": {
    "Addison County": 6,
    "Bennington County": 6,
    "Caledonia County": 9,
    "Chittenden County": 3,
    "Essex County": 9,
    "Franklin County": 3,
    "Grand Isle County": 3,
    "Lamoille County": 8,
    "Orange County": 9,
    "Orleans County": 9,
    "Rutland County": 7,
    "Washington County": 4,
    "Windham County": 7,
    "Windsor County": 7
  },
  "VA": {
    "Accomack County": 9,
    "Albemarle County": 3,
    "Alleghany County": 6,
    "Amelia County": 1,
    "Amherst County": 2,
    "Appomattox County": 2,
    "Arlington County": 1,
    "Augusta County": 3,
    "Bath County": 9,
    "Bedford County": 2,
    "Bland County": 8,
    "Botetourt County": 2,
    "Brunswick County": 8,
    "Buchanan County": 9,
    "Buckingham County": 8,
    "Campbell County": 2,
    "Caroline County": 8,
    "Carroll County": 6,
    "Charles City County": 1,
    "Charlotte County": 8,
    "Chesterfield County": 1,
    "Clarke County": 1,
    "Craig County": 2,
    "Culpeper County": 1,
    "Cumberland County": 8,
    "Dickenson County": 9,
    "Dinwiddie County": 1,
    "Essex County": 8,
    "Fairfax County": 1,
    "Fauquier County": 1,
    "Floyd County": 3,
    "Fluvanna County": 3,
    "Franklin County": 2,
    "Frederick County": 3,
    "Giles County": 3,
    "Gloucester County": 1,
    "Goochland County": 1,
    "Grayson County": 9,
    "Greene County": 3,
    "Greensville County": 6,
    "Halifax County": 6,
    "Hanover County": 1,
    "Henrico County": 1,
    "Henry County": 4,
    "Highland County": 8,
    "Isle of Wight County": 1,
    "James City County": 1,
    "King and Queen County": 1,
    "King George County": 8,
    "King William County": 1,
    "Lancaster County": 9,
    "Lee County": 8,
    "Loudoun County": 1,
    "Louisa County": 8,
    "Lunenburg County": 9,
    "Madison County": 8,
    "Mathews County": 1,
    "Mecklenburg County": 7,
    "Middlesex County": 8,
    "Montgomery County": 3,
    "Nelson County": 3,
    "New Kent County": 1,
    "Northampton County": 8,
    "Northumberland County": 9,
    "Nottoway County": 8,
    "Orange County": 6,
    "Page County": 8,
    "Patrick County": 8,
    "Pittsylvania County": 4,
    "Powhatan County": 1,
    "Prince Edward County": 6,
    "Prince George County": 1,
    "Prince William County": 1,
    "Pulaski County": 3,
    "Rappahannock County": 1,
    "Richmond County": 9,
    "Roanoke County": 2,
    "Rockbridge County": 6,
    "Rockingham County": 3,
    "Russell County": 8,
    "Scott County": 2,
    "Shenandoah County": 6,
    "Smyth County": 7,
    "Southampton County": 6,
    "Spotsylvania County": 1,
    "Stafford County": 1,
    "Surry County": 1,
    "Sussex County": 1,
    "Tazewell County": 7,
    "Warren County": 1,
    "Washington County": 2,
    "Westmoreland County": 8,
    "Wise County": 7,
    "Wythe County": 6,
    "York County": 1,
    "Alexandria city": 1,
    "Bristol city": 2,
    "Buena Vista city": 6,
    "Charlottesville city": 3,
    "Chesapeake city": 1,
    "Colonial Heights city": 1,
    "Covington city": 6,
    "Danville city": 4,
    "Emporia city": 6,
    "Fairfax city": 1,
    "Falls Church city": 1,
    "Franklin city": 6,
    "Fredericksburg city": 1,
    "Galax city": 6,
    "Hampton city": 1,
    "Harrisonburg city": 3,
    "Hopewell city": 1,
    "Lexington city": 6,
    "Lynchburg city": 2,
    "Manassas city": 1,
    "Manassas Park city": 1,
    "Martinsville city": 4,
    "Newport News city": 1,
    "Norfolk city": 1,
    "Norton city": 7,
    "Petersburg city": 1,
    "Poquoson city": 1,
    "Portsmouth city": 1,
    "Radford city": 3,
    "Richmond city": 1,
    "Roanoke city": 2,
    "Salem city": 2,
    "Staunton city": 3,
    "Suffolk city": 1,
    "Virginia Beach city": 1,
    "Waynesboro city": 3,
    "Williamsburg city": 1,
    "Winchester city": 3
  },
  "WA": {
    "Adams County": 6,
    "Asotin County": 3,
    "Benton County": 2,
    "Chelan County": 3,
    "Clallam County": 5,
    "Clark County": 1,
    "Columbia County": 8,
    "Cowlitz County": 3,
    "Douglas County": 3,
    "Ferry County": 8,
    "Franklin County": 2,
    "Garfield County": 8,
    "Grant County": 5,
    "Grays Harbor County": 4,
    "Island County": 4,
    "Jefferson County": 6,
    "King County": 1,
    "Kitsap County": 2,
    "Kittitas County": 4,
    "Klickitat County": 9,
    "Lewis County": 4,
    "Lincoln County": 8,
    "Mason County": 4,
    "Okanogan County": 6,
    "Pacific County": 7,
    "Pend Oreille County": 8,
    "Pierce County": 1,
    "San Juan County": 9,
    "Skagit County": 3,
    "Skamania County": 1,
    "Snohomish County": 1,
    "Spokane County": 2,
    "Stevens County": 2,
    "Thurston County": 2,
    "Wahkiakum County": 8,
    "Walla Walla County": 3,
    "Whatcom County": 3,
    "Whitman County": 4,
    "Yakima County": 2
  },
  "WV": {
    "Barbour County": 9,
    "Berkeley County": 2,
    "Boone County": 3,
    "Braxton County": 8,
    "Brooke County": 3,
    "Cabell County": 2,
    "Calhoun County": 8,
    "Clay County": 3,
    "Doddridge County": 9,
    "Fayette County": 3,
    "Gilmer County": 9,
    "Grant County": 9,
    "Greenbrier County": 6,
    "Hampshire County": 3,
    "Hancock County": 3,
    "Hardy County": 8,
    "Harrison County": 5,
    "Jackson County": 8,
    "Jefferson County": 1,
    "Kanawha County": 3,
    "Lewis County": 9,
    "Lincoln County": 8,
    "Logan County": 6,
    "McDowell County": 9,
    "Marion County": 4,
    "Marshall County": 3,
    "Mason County": 6,
    "Mercer County": 4,
    "Mineral County": 7,
    "Mingo County": 8,
    "Monongalia County": 3,
    "Monroe County": 8,
    "Morgan County": 2,
    "Nicholas County": 8,
    "Ohio County": 3,
    "Pendleton County": 8,
    "Pleasants County": 8,
    "Pocahontas County": 9,
    "Preston County": 3,
    "Putnam County": 2,
    "Raleigh County": 3,
    "Randolph County": 7,
    "Ritchie County": 8,
    "Roane County": 8,
    "Summers County": 8,
    "Taylor County": 6,
    "Tucker County": 9,
    "Tyler County": 9,
    "Upshur County": 7,
    "Wayne County": 2,
    "Webster County": 9,
    "Wetzel County": 7,
    "Wirt County": 3,
    "Wood County": 3,
    "Wyoming County": 8
  },
  "WI": {
    "Adams County": 8,
    "Ashland County": 7,
    "Barron County": 6,
    "Bayfield County": 8,
    "Brown County": 2,
    "Buffalo County": 8,
    "Burnett County": 8,
    "Calumet County": 3,
    "Chippewa County": 3,
    "Clark County": 8,
    "Columbia County": 2,
    "Crawford County": 6,
    "Dane County": 2,
    "Dodge County": 4,
    "Door County": 6,
    "Douglas County": 2,
    "Dunn County": 6,
    "Eau Claire County": 3,
    "Florence County": 9,
    "Fond du Lac County": 3,
    "Forest County": 9,
    "Grant County": 6,
    "Green County": 2,
    "Green Lake County": 6,
    "Iowa County": 2,
    "Iron County": 9,
    "Jackson County": 8,
    "Jefferson County": 4,
    "Juneau County": 8,
    "Kenosha County": 3,
    "Kewaunee County": 2,
    "La Crosse County": 3,
    "Lafayette County": 8,
    "Langlade County": 6,
    "Lincoln County": 6,
    "Manitowoc County": 4,
    "Marathon County": 3,
    "Marinette County": 6,
    "Marquette County": 8,
    "Menominee County": 9,
    "Milwaukee County": 1,
    "Monroe County": 4,
    "Oconto County": 2,
    "Oneida County": 7,
    "Outagamie County": 3,
    "Ozaukee County": 1,
    "Pepin County": 8,
    "Pierce County": 1,
    "Polk County": 8,
    "Portage County": 4,
    "Price County": 9,
    "Racine County": 3,
    "Richland County": 8,
    "Rock County": 3,
    "Rusk County": 8,
    "St. Croix County": 1,
    "Sauk County": 4,
    "Sawyer County": 9,
    "Shawano County": 6,
    "Sheboygan County": 3,
    "Taylor County": 8,
    "Trempealeau County": 8,
    "Vernon County": 3,
    "Vilas County": 9,
    "Walworth County": 4,
    "Washburn County": 8,
    "Washington County": 1,
    "Waukesha County": 1,
    "Waupaca County": 6,
    "Waushara County": 8,
    "Winnebago County": 3,
    "Wood County": 4
  },
  "WY": {
    "Albany County": 4,
    "Big Horn County": 9,
    "Campbell County": 5,
    "Carbon County": 7,
    "Converse County": 6,
    "Crook County": 9,
    "Fremont County": 7,
    "Goshen County": 7,
    "Hot Springs County": 9,
    "Johnson County": 9,
    "Laramie County": 3,
    "Lincoln County": 9,
    "Natrona County": 3,
    "Niobrara County": 9,
    "Park County": 7,
    "Platte County": 8,
    "Sheridan County": 7,
    "Sublette County": 9,
    "Sweetwater County": 5,
    "Teton County": 7,
    "Uinta County": 7,
    "Washakie County": 9,
    "Weston County": 9
  },
  "AS": {
    "Eastern District": 7,
    "Manu'a District": 9,
    "Western District": 5
  },
  "GU": {
    "Guam": 5
  },
  "MP": {
    "Northern Islands Municipality": 9,
    "Rota Municipality": 9,
    "Saipan Municipality": 5,
    "Tinian Municipality": 9
  },
  "PR": {
    "Adjuntas Municipio": 6,
    "Aguada Municipio": 2,
    "Aguadilla Municipio": 2,
    "Aguas Buenas Municipio": 1,
    "Aibonito Municipio": 1,
    "A�asco Municipio": 2,
    "Arecibo Municipio": 3,
    "Arroyo Municipio": 3,
    "Barceloneta Municipio": 1,
    "Barranquitas Municipio": 1,
    "Bayam�n Municipio": 1,
    "Cabo Rojo Municipio": 3,
    "Caguas Municipio": 1,
    "Camuy Municipio": 3,
    "Can�vanas Municipio": 1,
    "Carolina Municipio": 1,
    "Cata�o Municipio": 1,
    "Cayey Municipio": 1,
    "Ceiba Municipio": 1,
    "Ciales Municipio": 1,
    "Cidra Municipio": 1,
    "Coamo Municipio": 4,
    "Comer�o Municipio": 1,
    "Corozal Municipio": 1,
    "Culebra Municipio": 9,
    "Dorado Municipio": 1,
    "Fajardo Municipio": 1,
    "Florida Municipio": 1,
    "Gu�nica Municipio": 6,
    "Guayama Municipio": 3,
    "Guayanilla Municipio": 2,
    "Guaynabo Municipio": 1,
    "Gurabo Municipio": 1,
    "Hatillo Municipio": 3,
    "Hormigueros Municipio": 3,
    "Humacao Municipio": 1,
    "Isabela Municipio": 2,
    "Jayuya Municipio": 6,
    "Juana D�az Municipio": 2,
    "Juncos Municipio": 1,
    "Lajas Municipio": 3,
    "Lares Municipio": 4,
    "Las Mar�as Municipio": 8,
    "Las Piedras Municipio": 1,
    "Lo�za Municipio": 1,
    "Luquillo Municipio": 1,
    "Manat� Municipio": 1,
    "Maricao Municipio": 8,
    "Maunabo Municipio": 1,
    "Mayag�ez Municipio": 3,
    "Moca Municipio": 2,
    "Morovis Municipio": 1,
    "Naguabo Municipio": 1,
    "Naranjito Municipio": 1,
    "Orocovis Municipio": 1,
    "Patillas Municipio": 3,
    "Pe�uelas Municipio": 2,
    "Ponce Municipio": 2,
    "Quebradillas Municipio": 3,
    "Rinc�n Municipio": 2,
    "R�o Grande Municipio": 1,
    "Sabana Grande Municipio": 3,
    "Salinas Municipio": 4,
    "San Germ�n Municipio": 3,
    "San Juan Municipio": 1,
    "San Lorenzo Municipio": 1,
    "San Sebasti�n Municipio": 2,
    "Santa Isabel Municipio": 6,
    "Toa Alta Municipio": 1,
    "Toa Baja Municipio": 1,
    "Trujillo Alto Municipio": 1,
    "Utuado Municipio": 6,
    "Vega Alta Municipio": 1,
    "Vega Baja Municipio": 1,
    "Vieques Municipio": 6,
    "Villalba Municipio": 2,
    "Yabucoa Municipio": 1,
    "Yauco Municipio": 2
  },
  "VI": {
    "St. Croix Island": 5,
    "St. John Island": 9,
    "St. Thomas Island": 5
  }
};

// Export the data for use in other scripts
if (typeof module !== 'undefined') {
  module.exports = { countyData };
}
